#!/bin/bash

# PDF Verification Script
# Checks what PDFs exist and their status

echo "╔══════════════════════════════════════════════════════════════════════════════╗"
echo "║                                                                              ║"
echo "║                        📋 PDF Verification Report                           ║"
echo "║                                                                              ║"
echo "╚══════════════════════════════════════════════════════════════════════════════╝"
echo ""

# Check for issue PDFs
echo "🔍 Checking Issue PDFs (REAL - from GitHub)..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

issue_pdfs=$(ls issue-*.pdf 2>/dev/null)
if [ -n "$issue_pdfs" ]; then
    echo "✅ Found issue PDFs:"
    echo ""
    for pdf in $issue_pdfs; do
        size=$(ls -lh "$pdf" | awk '{print $5}')
        date=$(ls -lh "$pdf" | awk '{print $6, $7, $8}')
        pages=$(file "$pdf" | grep -o '[0-9]* page' | grep -o '[0-9]*')
        echo "   📄 $pdf"
        echo "      Size: $size | Pages: ${pages:-?} | Modified: $date"
        echo ""
    done
else
    echo "❌ No issue PDFs found"
    echo ""
fi

# Check for real solution PDFs (with issue numbers)
echo "🔍 Checking Solution PDFs (REAL - from Stack Overflow)..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

real_solution_pdfs=$(ls solution-*-issue-*.pdf 2>/dev/null)
if [ -n "$real_solution_pdfs" ]; then
    echo "✅ Found real solution PDFs:"
    echo ""
    for pdf in $real_solution_pdfs; do
        size=$(ls -lh "$pdf" | awk '{print $5}')
        date=$(ls -lh "$pdf" | awk '{print $6, $7, $8}')
        pages=$(file "$pdf" | grep -o '[0-9]* page' | grep -o '[0-9]*')
        echo "   💡 $pdf"
        echo "      Size: $size | Pages: ${pages:-?} | Modified: $date"
        echo ""
    done
else
    echo "❌ No real solution PDFs found"
    echo "   This is normal if:"
    echo "   • No Stack Overflow solutions exist for analyzed issues"
    echo "   • Issues are feature requests (not bugs)"
    echo "   • Issues are too new or too specific"
    echo ""
fi

# Check for mock solution PDFs (no issue numbers)
echo "🔍 Checking Mock Solution PDFs (MOCK - for testing)..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

mock_solution_pdfs=$(ls solution-[0-9].pdf 2>/dev/null)
if [ -n "$mock_solution_pdfs" ]; then
    echo "✅ Found mock solution PDFs:"
    echo ""
    for pdf in $mock_solution_pdfs; do
        size=$(ls -lh "$pdf" | awk '{print $5}')
        date=$(ls -lh "$pdf" | awk '{print $6, $7, $8}')
        pages=$(file "$pdf" | grep -o '[0-9]* page' | grep -o '[0-9]*')
        echo "   🧪 $pdf (MOCK - test data)"
        echo "      Size: $size | Pages: ${pages:-?} | Modified: $date"
        echo ""
    done
    echo "   ℹ️  These are generated by: npx tsx test-solution-pdfs.ts"
    echo ""
else
    echo "❌ No mock solution PDFs found"
    echo "   Generate them with: npx tsx test-solution-pdfs.ts"
    echo ""
fi

# Summary
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 Summary"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

issue_count=$(ls issue-*.pdf 2>/dev/null | wc -l | tr -d ' ')
real_solution_count=$(ls solution-*-issue-*.pdf 2>/dev/null | wc -l | tr -d ' ')
mock_solution_count=$(ls solution-[0-9].pdf 2>/dev/null | wc -l | tr -d ' ')

echo "   Issue PDFs (REAL):          $issue_count"
echo "   Solution PDFs (REAL):       $real_solution_count"
echo "   Solution PDFs (MOCK):       $mock_solution_count"
echo ""

# Specific check for issue #33898
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎯 Issue #33898 Status"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

if [ -f "issue-33898-analysis.pdf" ]; then
    size=$(ls -lh issue-33898-analysis.pdf | awk '{print $5}')
    date=$(ls -lh issue-33898-analysis.pdf | awk '{print $6, $7, $8}')
    echo "   ✅ Issue PDF: issue-33898-analysis.pdf"
    echo "      Size: $size | Modified: $date"
else
    echo "   ❌ Issue PDF: Not found"
fi

solution_33898=$(ls solution-*-issue-33898.pdf 2>/dev/null | wc -l | tr -d ' ')
if [ "$solution_33898" -gt 0 ]; then
    echo "   ✅ Solution PDFs: $solution_33898 found"
else
    echo "   ❌ Solution PDFs: None (no Stack Overflow solutions found)"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "💡 Quick Commands"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   # Generate PDFs for an issue"
echo "   npm run auto-solutions <github-issue-url>"
echo ""
echo "   # Generate mock PDFs for testing"
echo "   npx tsx test-solution-pdfs.ts"
echo ""
echo "   # View issue #33898 PDF"
echo "   open issue-33898-analysis.pdf"
echo ""
echo "   # Clean up all PDFs"
echo "   rm -f *.pdf"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
