/**
 * 🚀 PROFESSIONAL ZIP GENERATOR SERVICE
 * Creates complete, production-ready project ZIP files
 * Perfect for hackathon demos and sponsor presentations
 */

import JSZip from 'jszip';
import { saveAs } from 'file-saver';

interface ProjectFile {
  name: string;
  content: string;
  type: 'component' | 'style' | 'config' | 'page' | 'documentation';
}

interface ProjectStructure {
  name: string;
  description: string;
  framework: string;
  author: string;
  files: ProjectFile[];
  dependencies: Record<string, string>;
  devDependencies: Record<string, string>;
  scripts: Record<string, string>;
}

export class ZipGenerator {
  /**
   * 🎯 GENERATE COMPLETE PROJECT ZIP
   */
  static async generateProjectZip(project: ProjectStructure): Promise<void> {
    const zip = new JSZip();
    
    // 📁 Create project folder structure
    const projectFolder = zip.folder(project.name.toLowerCase().replace(/\s+/g, '-'));
    if (!projectFolder) throw new Error('Failed to create project folder');

    // 📄 Add all project files
    this.addProjectFiles(projectFolder, project);
    
    // 📦 Add package.json
    this.addPackageJson(projectFolder, project);
    
    // 📚 Add comprehensive README.md
    this.addReadmeFile(projectFolder, project);
    
    // ⚙️ Add configuration files
    this.addConfigFiles(projectFolder, project);
    
    // 🚀 Add deployment files
    this.addDeploymentFiles(projectFolder, project);
    
    // 📋 Add installation script
    this.addInstallationScript(projectFolder, project);

    // 💾 Generate and download ZIP
    const content = await zip.generateAsync({ type: 'blob' });
    const fileName = `${project.name.toLowerCase().replace(/\s+/g, '-')}-complete-project.zip`;
    
    saveAs(content, fileName);
    
    console.log(`🎉 Generated complete project: ${fileName}`);
  }

  /**
   * 📄 ADD PROJECT FILES
   */
  private static addProjectFiles(folder: JSZip, project: ProjectStructure): void {
    // Create src folder
    const srcFolder = folder.folder('src');
    if (!srcFolder) return;

    // Add main files
    project.files.forEach(file => {
      if (file.type === 'component' || file.type === 'page') {
        srcFolder.file(file.name, file.content);
      } else if (file.type === 'style') {
        srcFolder.file(file.name, file.content);
      } else if (file.type === 'config') {
        folder.file(file.name, file.content);
      }
    });

    // Add index.html
    srcFolder.file('index.html', this.generateIndexHtml(project));
    
    // Add main.tsx
    srcFolder.file('main.tsx', this.generateMainTsx(project));
    
    // Add vite-env.d.ts
    srcFolder.file('vite-env.d.ts', this.generateViteEnv());
  }

  /**
   * 📦 ADD PACKAGE.JSON
   */
  private static addPackageJson(folder: JSZip, project: ProjectStructure): void {
    const packageJson = {
      name: project.name.toLowerCase().replace(/\s+/g, '-'),
      version: '1.0.0',
      description: project.description,
      type: 'module',
      scripts: {
        dev: 'vite',
        build: 'tsc && vite build',
        preview: 'vite preview',
        lint: 'eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0',
        ...project.scripts
      },
      dependencies: {
        react: '^18.2.0',
        'react-dom': '^18.2.0',
        ...project.dependencies
      },
      devDependencies: {
        '@types/react': '^18.2.43',
        '@types/react-dom': '^18.2.17',
        '@typescript-eslint/eslint-plugin': '^6.14.0',
        '@typescript-eslint/parser': '^6.14.0',
        '@vitejs/plugin-react': '^4.2.1',
        eslint: '^8.55.0',
        'eslint-plugin-react-hooks': '^4.6.0',
        'eslint-plugin-react-refresh': '^0.4.5',
        typescript: '^5.2.2',
        vite: '^5.0.8',
        ...project.devDependencies
      },
      keywords: ['ai-generated', 'react', 'typescript', 'vite', 'hackathon'],
      author: project.author,
      license: 'MIT',
      repository: {
        type: 'git',
        url: 'https://github.com/your-username/your-repo.git'
      }
    };

    folder.file('package.json', JSON.stringify(packageJson, null, 2));
  }

  /**
   * 📚 ADD COMPREHENSIVE README
   */
  private static addReadmeFile(folder: JSZip, project: ProjectStructure): void {
    const readme = `# 🤖 ${project.name}

> **Generated by Agentic AI Platform** - The future of code generation!

![AI Generated](https://img.shields.io/badge/AI-Generated-blue?style=for-the-badge&logo=robot)
![React](https://img.shields.io/badge/React-18.2.0-61DAFB?style=for-the-badge&logo=react)
![TypeScript](https://img.shields.io/badge/TypeScript-5.2.2-3178C6?style=for-the-badge&logo=typescript)
![Vite](https://img.shields.io/badge/Vite-5.0.8-646CFF?style=for-the-badge&logo=vite)

## 📝 Description

${project.description}

## ✨ Features

- 🤖 **AI-Generated Code** - Complete frontend application created by advanced AI
- ⚡ **Modern React 18** - Built with the latest React features and hooks
- 🔷 **TypeScript** - Full type safety and better developer experience
- 🎨 **Modern CSS** - Beautiful styling with animations and responsive design
- 🚀 **Vite Build Tool** - Lightning-fast development and build process
- 📱 **Responsive Design** - Works perfectly on all devices
- 🔧 **Production Ready** - Clean, maintainable, and scalable code
- 🎯 **Performance Optimized** - Fast loading and smooth interactions

## 🛠️ Tech Stack

| Technology | Version | Purpose |
|------------|---------|---------|
| **React** | 18.2.0 | Frontend framework |
| **TypeScript** | 5.2.2 | Type safety |
| **Vite** | 5.0.8 | Build tool |
| **CSS3** | Latest | Styling |
| **ESLint** | 8.55.0 | Code linting |

## 🚀 Quick Start

### Prerequisites

Make sure you have the following installed:
- **Node.js** (v18 or higher) - [Download here](https://nodejs.org/)
- **npm** or **yarn** - Comes with Node.js

### Installation

1. **Extract the ZIP file**
   \`\`\`bash
   # Extract to your desired location
   unzip ${project.name.toLowerCase().replace(/\s+/g, '-')}-complete-project.zip
   cd ${project.name.toLowerCase().replace(/\s+/g, '-')}
   \`\`\`

2. **Install dependencies**
   \`\`\`bash
   npm install
   # or
   yarn install
   \`\`\`

3. **Start development server**
   \`\`\`bash
   npm run dev
   # or
   yarn dev
   \`\`\`

4. **Open in browser**
   \`\`\`
   http://localhost:5173
   \`\`\`

### Build for Production

\`\`\`bash
# Build the project
npm run build

# Preview the build
npm run preview
\`\`\`

## 📁 Project Structure

\`\`\`
${project.name.toLowerCase().replace(/\s+/g, '-')}/
├── 📁 src/
│   ├── 📄 App.tsx          # Main application component
│   ├── 🎨 App.css          # Application styles
│   ├── 📄 main.tsx         # Application entry point
│   ├── 🌐 index.html       # HTML template
│   └── 📝 vite-env.d.ts    # Vite type definitions
├── 📦 package.json         # Dependencies and scripts
├── ⚙️ tsconfig.json        # TypeScript configuration
├── ⚙️ vite.config.ts       # Vite configuration
├── ⚙️ eslint.config.js     # ESLint configuration
├── 🚀 vercel.json          # Vercel deployment config
├── 🚀 netlify.toml         # Netlify deployment config
├── 📚 README.md            # This file
└── 🛠️ install.sh           # Quick installation script
\`\`\`

## 🎨 Customization

### Styling
- Modify \`src/App.css\` for custom styles
- The project uses modern CSS with:
  - CSS Grid and Flexbox
  - CSS Variables
  - Animations and transitions
  - Responsive design

### Components
- Main component: \`src/App.tsx\`
- Add new components in the \`src/\` directory
- Follow React best practices and TypeScript conventions

### Configuration
- **Vite config**: \`vite.config.ts\`
- **TypeScript config**: \`tsconfig.json\`
- **ESLint config**: \`eslint.config.js\`

## 🚀 Deployment

### Vercel (Recommended)
1. Install Vercel CLI: \`npm i -g vercel\`
2. Run: \`vercel\`
3. Follow the prompts

### Netlify
1. Build the project: \`npm run build\`
2. Drag and drop the \`dist\` folder to [Netlify](https://netlify.com)

### GitHub Pages
1. Install gh-pages: \`npm install --save-dev gh-pages\`
2. Add to package.json scripts: \`"deploy": "gh-pages -d dist"\`
3. Run: \`npm run build && npm run deploy\`

### Other Platforms
- **Firebase Hosting**
- **AWS S3 + CloudFront**
- **DigitalOcean App Platform**
- **Heroku**

## 🔧 Development

### Available Scripts

| Script | Description |
|--------|-------------|
| \`npm run dev\` | Start development server |
| \`npm run build\` | Build for production |
| \`npm run preview\` | Preview production build |
| \`npm run lint\` | Run ESLint |

### Development Tips

1. **Hot Reload**: Changes are automatically reflected in the browser
2. **TypeScript**: Use TypeScript for better code quality
3. **ESLint**: Follow the linting rules for consistent code
4. **Performance**: Use React DevTools for performance optimization

## 🤖 AI Generation Details

This project was generated using **Agentic AI Platform** with the following prompt:

> "${project.description}"

### AI Features Used:
- 🧠 **Smart Code Generation** - Context-aware component creation
- 🎨 **Intelligent Styling** - Modern CSS with best practices
- 📦 **Dependency Management** - Optimal package selection
- 🔧 **Configuration Setup** - Production-ready configurations
- 📚 **Documentation** - Comprehensive README and comments

## 🆘 Troubleshooting

### Common Issues

**Port already in use**
\`\`\`bash
# Kill process on port 5173
npx kill-port 5173
# Or use a different port
npm run dev -- --port 3000
\`\`\`

**Module not found**
\`\`\`bash
# Clear node_modules and reinstall
rm -rf node_modules package-lock.json
npm install
\`\`\`

**Build errors**
\`\`\`bash
# Check TypeScript errors
npx tsc --noEmit
# Fix ESLint issues
npm run lint -- --fix
\`\`\`

### Getting Help

- 📖 [React Documentation](https://react.dev/)
- 📖 [TypeScript Documentation](https://www.typescriptlang.org/docs/)
- 📖 [Vite Documentation](https://vitejs.dev/)
- 🐛 [Create an Issue](https://github.com/your-username/your-repo/issues)

## 📄 License

This project is licensed under the MIT License - see the [LICENSE](LICENSE) file for details.

## 🙏 Acknowledgments

- **Agentic AI Platform** - For generating this amazing project
- **React Team** - For the incredible React framework
- **Vite Team** - For the blazing fast build tool
- **TypeScript Team** - For making JavaScript better

## 🌟 Show Your Support

If you found this project helpful, please give it a ⭐ on GitHub!

---

**Generated with ❤️ by [Agentic AI Platform](https://your-platform-url.com)**

*Ready to build something amazing? Start coding! 🚀*
`;

    folder.file('README.md', readme);
  }

  /**
   * ⚙️ ADD CONFIGURATION FILES
   */
  private static addConfigFiles(folder: JSZip, project: ProjectStructure): void {
    // TypeScript config
    const tsConfig = {
      compilerOptions: {
        target: 'ES2020',
        useDefineForClassFields: true,
        lib: ['ES2020', 'DOM', 'DOM.Iterable'],
        module: 'ESNext',
        skipLibCheck: true,
        moduleResolution: 'bundler',
        allowImportingTsExtensions: true,
        resolveJsonModule: true,
        isolatedModules: true,
        noEmit: true,
        jsx: 'react-jsx',
        strict: true,
        noUnusedLocals: true,
        noUnusedParameters: true,
        noFallthroughCasesInSwitch: true
      },
      include: ['src'],
      references: [{ path: './tsconfig.node.json' }]
    };
    folder.file('tsconfig.json', JSON.stringify(tsConfig, null, 2));

    // Vite config
    const viteConfig = `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  server: {
    port: 5173,
    open: true
  },
  build: {
    outDir: 'dist',
    sourcemap: true
  }
})`;
    folder.file('vite.config.ts', viteConfig);

    // ESLint config
    const eslintConfig = `import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'

export default tseslint.config(
  { ignores: ['dist'] },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      'react-refresh/only-export-components': [
        'warn',
        { allowConstantExport: true },
      ],
    },
  },
)`;
    folder.file('eslint.config.js', eslintConfig);

    // .gitignore
    const gitignore = `# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
lerna-debug.log*

node_modules
dist
dist-ssr
*.local

# Editor directories and files
.vscode/*
!.vscode/extensions.json
.idea
.DS_Store
*.suo
*.ntvs*
*.njsproj
*.sln
*.sw?

# Environment variables
.env
.env.local
.env.development.local
.env.test.local
.env.production.local`;
    folder.file('.gitignore', gitignore);
  }

  /**
   * 🚀 ADD DEPLOYMENT FILES
   */
  private static addDeploymentFiles(folder: JSZip, project: ProjectStructure): void {
    // Vercel config
    const vercelConfig = {
      buildCommand: 'npm run build',
      outputDirectory: 'dist',
      framework: 'vite'
    };
    folder.file('vercel.json', JSON.stringify(vercelConfig, null, 2));

    // Netlify config
    const netlifyConfig = `[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200`;
    folder.file('netlify.toml', netlifyConfig);
  }

  /**
   * 🛠️ ADD INSTALLATION SCRIPT
   */
  private static addInstallationScript(folder: JSZip, project: ProjectStructure): void {
    const installScript = `#!/bin/bash

# 🚀 ${project.name} - Quick Installation Script
# Generated by Agentic AI Platform

echo "🤖 Welcome to ${project.name}!"
echo "🚀 Starting installation process..."

# Check if Node.js is installed
if ! command -v node &> /dev/null; then
    echo "❌ Node.js is not installed. Please install Node.js from https://nodejs.org/"
    exit 1
fi

# Check Node.js version
NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 18 ]; then
    echo "⚠️  Node.js version 18 or higher is required. Current version: $(node -v)"
    echo "Please update Node.js from https://nodejs.org/"
    exit 1
fi

echo "✅ Node.js $(node -v) detected"

# Install dependencies
echo "📦 Installing dependencies..."
if command -v yarn &> /dev/null; then
    echo "Using Yarn..."
    yarn install
else
    echo "Using npm..."
    npm install
fi

echo ""
echo "🎉 Installation complete!"
echo ""
echo "🚀 To start the development server:"
echo "   npm run dev"
echo ""
echo "🌐 The app will open at: http://localhost:5173"
echo ""
echo "📚 For more information, check the README.md file"
echo ""
echo "Happy coding! 💻✨"`;

    folder.file('install.sh', installScript);
  }

  /**
   * 🌐 GENERATE INDEX.HTML
   */
  private static generateIndexHtml(project: ProjectStructure): string {
    return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="${project.description}" />
    <meta name="author" content="${project.author}" />
    <meta name="keywords" content="ai-generated, react, typescript, ${project.framework}" />
    <title>${project.name}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>`;
  }

  /**
   * 📄 GENERATE MAIN.TSX
   */
  private static generateMainTsx(project: ProjectStructure): string {
    return `import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.tsx'
import './App.css'

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)`;
  }

  /**
   * 📝 GENERATE VITE-ENV.D.TS
   */
  private static generateViteEnv(): string {
    return `/// <reference types="vite/client" />`;
  }
}

export default ZipGenerator;